version: "3.9"
services:
  product:
    container_name: ecomm-product
    build: ./product
    ports:
      -"3001:3001"

  account:
    container_name: ecomm-account
    build: ./account
    ports:
      -"3002:3002"

  mongo:
    container_name: mongo-alura
    image: mongo
    restart: always
    volumes:
      - db-mongo-alura:/data/db
    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  db-mongo-alura: