,version: "3.9"
services:
  product:
    container_name: ecomm-product
    build: ./product
    ports:
      - 3001:3001

  account:
    container_name: ecomm-account
    build: ./account
    ports:
      - 3002:3002

  mongo:
    container_name: mongo-alura
    image: mongo
    restart: always
    volumes:
      - db-mongo-alura:/data/db
    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  mysql:
    container_name: mysql-ecomm
    image: mysql
    restart: always
    volumes:
      - mysql-ecomm-volume:/var/lib/mysql
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: secret

volumes:
  db-mongo-alura:
  mysql-ecomm-volume: