version: "3.9"
services:
  mongodb:
    container_name: mongo-alura
    image: mongo
    restart: always
    volumes:
      - db-mongo-alura:/data/db
    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  mysql:
    container_name: mysql-ecomm
    image: mysql
    restart: always
    volumes:
      - mysql-ecomm-volume:/var/lib/mysql
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: secret

  redis:
    image: redis
    volumes:
    - redis_data:/data
    container_name: redis-ecomm
    restart: always
    ports:
    - 6379:6379

  product:
    container_name: ecomm-product
    build: ./product
    volumes:
      - ./product/:/app/ecomm-product
    ports:
      - 3001:3001
    depends_on:
      - mongodb

  account:
    container_name: ecomm-account
    build: ./account
    volumes:
      - ./account/:/app/ecomm-account
    ports:
      - 3002:3002
    depends_on:
      - mongodb
      - redis

  finance:
    container_name: ecomm-finance
    build: ./finance
    volumes:
      - ./finance/:/app/ecomm-finance
    ports:
      - 3003:3003
    depends_on:
      - mysql

  order:
    container_name: ecomm-order
    build: ./order
    volumes:
      - ./order/:/app/ecomm-order
    ports:
      - 3004:3004
    depends_on:
      - mongodb

volumes:
  db-mongo-alura:
  mysql-ecomm-volume:
  redis_data: