openapi: 3.0.3
info:
  title: Ecomm Products API
  description: 'API responsável pelas requisições nos produtos do e-commerce'
  version: 0.0.1
paths:
  /api/categories:
    get:
      summary: Recupera ID, nome e status de todas as categorias.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categories"
  /api/admin/categories:
    post:
      summary: Cria uma nova categoria.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        401:
          $ref: '#/components/responses/UnauthorizedError'
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
    Categories:
      type: array
      items:
        $ref: "#/components/schemas/Category"
  responses:
    UnauthorizedError:
      description: 'Usuário não autorizado.'
      content:
        application/json:
          example: 'Unauthorized'