openapi: 3.0.3
info:
  title: Ecomm Products API
  description: 'API responsável pelas requisições nos produtos do e-commerce'
  version: 0.0.1
  contact: 
    name: Matheus Leme
    email: matheus.santos@pagonxt.com
    url: https://github.com/LemeLHP
  license:
    name: Licença Pública
    url: https://www.gnu.org/licenses/gpl-3.0.html
paths:
  /api/categories:
    get:
      summary: Recupera ID, nome e status de todas as categorias.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categories"
  /api/admin/categories:
    post:
      summary: Cria uma nova categoria.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /api/categories/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: string
      required: true
    get:
      summary: Recupera uma categoria pelo ID.
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        404:
          $ref: '#/components/responses/NotFound'
  /api/admin/categories/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: string
      required: true
    put:
      summary: Atualiza categoria pelo ID.
      description: Atualiza todas as informações da categoria.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        200:
          description: Categoria atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Deleta uma categoria pelo ID.
      responses:
        200:
          description: Categoria deletada com sucesso.
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Ativa categoria.
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFound'
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        status:
          type: string
    Categories:
      type: array
      items:
        $ref: "#/components/schemas/Category"
  responses:
    UnauthorizedError:
      description: 'Usuário não autorizado.'
      content:
        application/json:
          example: 'Unauthorized'
    NotFound:
      description: 'Não encontrado.'
      content:
        application/json:
          example: 'Not Found'